### ISSUE TITLE
Needed survey list styling

### ISSUE THREAD

**Issue by tyliec** [CodeWithAloha/HIERR#204]
**Describe the bug**

Currently, the list of surveys a user can take looks like this:

![Image](https://github.com/CodeWithAloha/HIERR/assets/15609358/7af1f736-0f70-4861-8c1b-4fec0c003772)

A vertical list, with surveys stacked on top of each other.

**Expected behavior**

The UI/UX of this list is improved.

**Comment by avenmia** [comment]
This is fixed as part of https://github.com/CodeWithAloha/HIERR/pull/173
